version: "3.9"
   
services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
  
  web:
    build: .
    command: python manage.py makemigrations
    volumes:
      - static:/static/
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      
  nginx:
    build: ./nginx
    volumes:
        - static:/static
    ports:
        - "80:80"
    depends_on:
        - web
        
volumes:
    static:
    postgres_data: